###########
# site.title, site.path, site.url

title: "Dr. Jekyll's Themes"

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#    note: for root path use empty string e.g. '' - do NOT include trailing slash e.g. /
path:   ''
url:   "http://drjekyllthemes.github.io"


########
# more settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

permalink:  /news/:title.html

sass:
  sass_dir: css
  style:    expanded


include:
- _data

exclude:
- README.md
- _data/themes/README.md
- _data/themes/themes.yml


safe: true
lsi: false
