###########
# site.title, site.path, site.url

title: "Dr. Jekyll's Themes"

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#    note: for root path use empty string e.g. '' - do NOT include trailing slash e.g. /
path:    ''
baseurl: ''
url:   "http://drjekyllthemes.github.io"


defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author

collections:
  authors:
    output: true
    permalink: /:name


########
# more settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style:    expanded

plugins:
- jekyll-avatar


exclude:
- README.md


safe: true
lsi: false
